### PR TITLE
ASE engine for evaluation of energies and foces

### PR DESCRIPTION
**Pull request by stenczelt**
New engine for any ASE calculator, this is mainly a rebase and cleanup of #129

### CODE REVIEW

**Comment by stenczelt** [comment]
@leeping an integration test has been added, HCN transition state with XTB. I am not entirely happy with it, because XTB seems to conflict with the rest of the conda packages used for testing. So if it is OK to execute that test with a separate environment, for which I have added a pure XTB+ASE env file, then this can be considered complete and ready for review

**Comment by leeping** [comment]
Thanks a lot for your contribution (and reviving it as well!)  The engine looks nice and clean, and the code that imports the correct Calculator class based on user input is a nice touch.  I also ran your example calculation locally and it works.

Please take a look at the changes I made to `latest.yaml`.  I think it enables the installation of the full test env including rdkit, psi4, openmm, ase, xtb-python on my local machine (running Ubuntu 18.04).  I didn't change very much but putting psi4 and rdkit highest in the channel priority might have made a difference.

**Comment by leeping** [comment]
I'm afraid it's still a work in progress .. the installation worked perfectly on my local machine with both ase and xtb-python, but it hangs indefinitely on GH Actions.  I doubt it's due to the difference between the Ubuntu versions (I'm using 18.04 locally).  I'm now making changes incrementally from the "old" latest.yaml file in the hope that I could ultimately get it to work.  Playing trial and error with conda's environment solver is always a pain.

**Review by leeping — APPROVED** [review]

**Comment by leeping** [comment]
All right, it looks like the env setup is fully working now.  LGTM! :)

**Comment by stenczelt** [comment]
great, thanks!

**Pull request merged**
