### PR TITLE
Adding QUICK engine for geometry optimization calculations

### PR DESCRIPTION
**Pull request by akhilshajan**
Hi, 

I tried geomeTRIC with the QUantum Interaction Computational Kernel (QUICK) program developed by Götz lab at University of California San Diego and Merz lab at Michigan State University.I wanted to introduce QUICK to geomeTRIC so that anyone could use QUICK inputs for optimization calculations. Although it is not now utilized for transition states, it will be added in the future.

I tested with QUICK engine additions to geomeTRIC, and everything was successful. Could you please consider this pull request so that it is made public?

Thank you.

Best,
Akhil Shajan

### CODE REVIEW

**Comment by leeping** [comment]
Hello Akhil,

Thanks for opening this pull request!  Your codes are easy for me to understand, and I would be glad for geomeTRIC to include an interface to QUICK so users could use it for geometry optimizations.

There's a couple of things I'd like to see before we merge it into the main repository:

1) Could you please add an example calculation under the "examples/1-simple-examples" folder so that others have a convenient starting point for geometry optimizations using your interface?

2) Could you please add two unit tests for the following:
- `Molecule()` parses the QUICK input file and produces the correct result
- A simple QUICK geometry optimization converges to the expected result in an expected number of cycles; a water dimer will work as an example. This test calculation could be the same as the example.

- Lee-Ping

**Comment by akhilshajan** [comment]
I have added same example as for Gaussian using water dimer with the results from QUICK. It contains Water.tmp folder wherein the input file for quick is updated at each iteration.

I didn't understand what you wanted for Molecule() unit tests. Would you kindly elaborate?

**Comment by leeping** [comment]
Basically, the test should read in a QUICK input file as a Molecule object and check that `Molecule.xyzs` is correct (it should be a list with length 1, and the first element should be a Nx3 array of the positions in Angstroms).  It should also check that `Molecule.elem` has the correct atomic symbols.

Thanks for adding the example input.  Could you let me know why the spin and multiplicity are not specified in the second line?  Does it default to a neutral singlet?

**Comment by leeping** [comment]
Ah, one more thing: I don't think we can have the Molecule class assume that `.in` files default to QUICK input files instead of Q-Chem input files.  That's the reason why one of the unit tests is failing.  Is there any other file extension for QUICK input files that you could use, such as `.qkin`?

If you want to write some code to autodetect whether a provided file that ends in `.in` is a QUICK or Q-Chem input file, that could work as well.  (For example, see [this code that auto-detects whether a .xyz file is actually in TINKER format](https://github.com/leeping/geomeTRIC/blob/master/geometric/molecule.py#L2956).)  However it's not obvious to me how one could definitively distinguish a QUICK input file from a Q-Chem input file by the contents alone.

**Comment by akhilshajan** [comment]
I did the unit test for `Molecule( )`. These were the results for `Molecule.xyz`, `Molecule.elem`:
```
{'xyzs': [array([[ 0.85591, -1.38236,  0.31746],
       [ 1.67524, -1.84774,  0.4858 ],
       [ 1.11761, -0.46843,  0.20575],
       [-1.09863, -0.85837,  2.17319],
       [-0.4031 , -1.14608,  1.58184],
       [-1.08511,  0.09683,  2.11282]])], 
'elem': ['O', 'H', 'H', 'O', 'H', 'H'], 
'charge': 0, 'mult': 1}
```

I have changed the quick input extension to .qkin as well as made correction for charge and multiplicity where it takes 0 and 1 respectively by default if not specified in first line.

**Comment by leeping** [comment]
Thanks a lot.  Please add the codes for the Molecule() unit test into test_molecule.py inside [this folder](ttps://github.com/leeping/geomeTRIC/blob/master/geometric/tests/).  You will need the test function to refer to the input file that you've added in the example folder; the path to the example folder is given by the variable `exampled`.

Also please add a function to test the water dimer minimization in [test_minimize.py](https://github.com/leeping/geomeTRIC/blob/master/geometric/tests/test_minimize.py#L20).  You can use [this function](https://github.com/leeping/geomeTRIC/blob/master/geometric/tests/test_minimize.py#L20) (which uses Psi4) as a reference for writing your test function.  The test should only run if QUICK is present on the system.

These tests are very important because they prevent future contributions from breaking existing features.  They also take a long time to develop (sometimes, as long as the code itself) so I really appreciate you doing this.

**Comment by akhilshajan** [comment]
I have added the unit tests required. Could you please check it?

**Comment by leeping** [comment]
Thanks, I can see the tests now.  I don't think [this line](https://github.com/leeping/geomeTRIC/pull/148/files#diff-e33db5166b0a363897b458da4665fe8d966ba74cc6ac94ba2c79859317c55173R56) will work because QUICK is not a Python module that is imported; it is a command line program, right?  It would work better if you instead copied/modified the codes that check if TeraChem or Q-Chem are installed, because they are also command line programs.

Last thing to do is for me to install QUICK locally and check if I can get the optimizations to run.  After that I think we are good to merge.

**Comment by leeping** [comment]
Thanks a lot - I was able to get everything to work after making a few minor corrections on top of your changes.  Please check [this PR](https://github.com/akhilshajan/geomeTRIC/pull/1). If you merge my PR, I believe it will automatically apply the changes to your PR and we can merge it.

**Comment by akhilshajan** [comment]
Done!

**Pull request merged**
