### PR TITLE
QCEngine: compute return update

### PR DESCRIPTION
**Pull request by dgasmith**
We are planning to change the QCEngine return to an object representation of the QCSchema by default rather than a straight dictionary. This change will force a dictionary return so that this transition will not effect geomeTRIC.

### CODE REVIEW

**Comment by leeping** [comment]
Thanks; please let me know if I need to cut a new release.

- Lee-Ping

**Comment by leeping** [comment]
I see the following error message on Travis.  Could you please check it?
```
_________________________ test_run_json_psi4_hydrogen __________________________
localizer = '/home/travis/build/leeping/geomeTRIC/test_generated_files/test_run_json_psi4_hydrogen'
    @addons.using_qcengine
    @addons.using_psi4
    def test_run_json_psi4_hydrogen(localizer):
    
        molecule = {
            "geometry": [
                0.0,  0.0, -0.5,
                0.0,  0.0,  0.5,
            ],
            "symbols": ["H", "H"],
            "connectivity": [[0, 1, 1]]
        } # yapf: disable
    
        in_json_dict = _build_input(molecule, program="psi4", method="HF", basis="sto-3g")
    
        with open('in.json', 'w') as handle:
            json.dump(in_json_dict, handle, indent=2)
    
        out_json = geometric.run_json.geometric_run_json(in_json_dict)
    
        with open('out.json', 'w') as handle:
            json.dump(out_json, handle, indent=2)
    
>       assert out_json["success"], out_json["error"]
E       AssertionError: {'error_message': 'geomeTRIC run_json error:
E         Traceback (most recent call last):
E           File "/home/travis/build/leeping/g...: 1 validation error
E         psi4:qcvars
E           extra fields not permitted (type=value_error.extra)
E         
E         ', 'error_type': 'unknown'}
E       assert False
../../geometric/tests/test_run_json.py:233: AssertionError
------------------------------ Captured log call -------------------------------
```

**Comment by dgasmith** [comment]
Yup, my fault. Cascading changes through QCEngine/QCElemental. This is the last planned deprecation for awhile so the chances of these issues should stop after this release. Give me a few hours to clean this up.

**Comment by dgasmith** [comment]
All good, please review!

**Comment by leeping** [comment]
Thanks, everything looks good; merging.

**Pull request merged**
