### PR TITLE
Allows fragments for molecule input in psi4

### PR DESCRIPTION
**Pull request by alenaizan**
This allows defining molecular fragments in psi4 input with '--' to separate them.

### CODE REVIEW

**Comment by leeping** [comment]
Thanks, this is very nice.  To clarify, is your fragment definition in psi4 independent from the internal coordinate system?  It looks like the fragments are being passed directly to psi4 for computing single point properties.  I can see how this might be useful if you were doing embedding calculations and the like.

**Comment by leeping** [comment]
Can you provide a simple example calculation in the `examples` folder to show how this would work?

**Comment by alenaizan** [comment]
Please see here for details on geometry specification in psi4 for noncovalent systems: http://www.psicode.org/psi4manual/master/psithonmol.html#non-covalently-bonded-molecule-fragments

The current Psi4 input parser in geometric does not handle noncovalent fragments inputs and a few other things. If you don't use the '--' syntax or if use it with a method that does not require fragment decomposition then psi4 will treat the system as a single unit and choose a coordinate system accordingly.  

My specific motivation for this is that I am working in writing a many-body expansion code to compute energies and gradients of noncovalent clusters. The attached example shows you that you can estimate the counterpoise-corrected gradient of the system of a water trimer by computing gradients for up to two-body terms. This example works in a development version of psi4 at https://github.com/alenaizan/psi4. I should create a pull request to psi4 soon,  and until then I think I should not add an example in the ```example``` directory. Please note that if you replace the last line with ```g = gradient('scf')``` then you will get the gradient for the whole system and the example will work just fine.

**Comment by leeping** [comment]
Thank you for the information.  Just to be clear, your added code will affect how Psi4 computes the energy and gradient as you intend, but it will not affect how geomeTRIC sets up its internal coordinate system.  geomeTRIC does not use the internal coordinate system that is "internal" to Psi4.

If you are already working with separate molecules (i.e. your fragments are not bonded and well-separated), then geomeTRIC should already set up the coordinate system "correctly" based on distance criteria, but it is not guaranteed to be the same as the fragments you specified in the Psi4 input.

**Comment by alenaizan** [comment]
Yes, this is correct.

**Comment by leeping** [comment]
Prior to merging this PR, I think it would be ideal if you could add an example calculation that others could run using the main branch of Psi4 (which would involve merging your Psi4 branch in the near future).  Let me know what you think.

**Comment by alenaizan** [comment]
Well, I agree with you but this addition is harmless anyway. I don't know how long it will take me to finish up my psi4 branch; I need to test it more and fix a few things. Maybe I will create a new pull request to geometric with an example once I get my psi4 branch merged.

**Comment by leeping** [comment]
I agree it's a harmless addition, on the other hand I think it's beneficial for you to include an example with this PR; we can leave it open for now and you may add your example when it's ready.  That way, everyone will know how to use your new feature.  :)

**Comment by dgasmith** [comment]
Just wanted to chime in and add to @leeping's comment: harmless additions usually become technical debt. Examples are great, but tests are better to avoid said technical debt.

**Comment by leeping** [comment]
Recently I've become interested in making the MECI / MECP optimizer available for all of the engines.  One possible way to generate the different SCF solutions for the same geometry would be to use different SCF guesses, such as using fragment-based methods.  I think it would be nice if we could merge @alenaizan 's codes for this reason.  Could you add a simple example or test to this PR that shows how the fragment input works?

**Comment by alenaizan** [comment]
Thanks for the reminder. Please see the example input. The last three lines in the input file is a workaround to allow geometric to read the many-body expansion gradient, which is not printed in psi4 by default.

**Comment by leeping** [comment]
Thank you very much for adding the example.  Looks good to merge now.

**Pull request merged**
