### PR TITLE
Add default xyz filename to Params and use temp directory for dirname…

### LINKED ISSUE #135: [BUG] Running Transition=True fails with geometric_run_json
## Overview
Running `transition=True` fails with `geometric_run_json` because [this call](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/run_json.py#L249) (or the other similar call [here](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/run_json.py#L260)) instantiate an `Optimizer` with `dirname=None`. When the `calcEnergyForce` [calls calc_cartesian_hessian](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/optimize.py#L232) it passes `self.dirname` (which is None). The [first lines in calc_cartesian_hessian](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/normal_modes.py#L72-L73) attempt to lookup a previously calculated hessian and the `os.join` call fails with `TypeError` because it cannot join `None` as a valid directory path:

```
geomeTRIC run_json error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/geometric/run_json.py", line 253, in geometric_run_json
    geometric.optimize.Optimize(coords, M, IC, engine, None, params)
  File "/opt/conda/lib/python3.9/site-packages/geometric/optimize.py", line 705, in Optimize
    return optimizer.optimizeGeometry()
  File "/opt/conda/lib/python3.9/site-packages/geometric/optimize.py", line 623, in optimizeGeometry
    self.calcEnergyForce()
  File "/opt/conda/lib/python3.9/site-packages/geometric/optimize.py", line 232, in calcEnergyForce
    self.Hx0 = calc_cartesian_hessian(self.X, self.molecule, self.engine, self.dirname, read_data=True, verbose=self.params.verbose)
  File "/opt/conda/lib/python3.9/site-packages/geometric/normal_modes.py", line 72, in calc_cartesian_hessian
    hesstxt = os.path.join(dirname, "hessian", "hessian.txt")
  File "/opt/conda/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Will create a PR to fix this...

### PR DESCRIPTION
**Pull request by coltonbh**
… in geometric_run_json to enable transition=True in qcengine

Closes #135 

Adds a default `xyzout` filename and uses a temporary directory for writing the hessian when running `geometric_run_json`.

I added a test that mimics [test_transition](https://github.com/leeping/geomeTRIC/blob/master/geometric/tests/test_transition.py). The only change needed was that it requires more steps to converge. I'm guessing this is because of different default parameters to `psi4` when run on the command line and in json mode?

Please let me know any feedback or suggestions. Would be nice to support `transition=True` for json inputs :)

### CODE REVIEW

**Comment by leeping** [comment]
Hello Colton,

Sorry for the late reply, and thank you for this PR.  I'm definitely interested in having `geometric_run_json` support for the transition state optimization feature.  I'm currently planning on a future "1.0" release including support for TS optimization, and we can include your additions for `geometric_run_json` in that.  I might ask for your help in creating a unit test.

- Lee-Ping

**Comment by coltonbh** [comment]
Sounds great! Let me know how you'd like to proceed when ready. I'm keen to enhance `qcschema/engine` support since I use geomeTRIC quite heavily in a number of integrations. Thanks for the reply!

**Comment by leeping** [comment]
I made direct changes to the files.  We'll use a modified version of the test that uses a provided Hessian so it runs faster.  Looks good to merge now.  Thanks a lot!

**Review by leeping — APPROVED** [review]

**Comment by coltonbh** [comment]
You're welcome!

**Pull request merged**
