### PR TITLE
Unify Optimizer and OptObject into a single class

### PR DESCRIPTION
**Pull request by leeping**
The more I thought about the recent reorganization of the main optimizer loop into two classes (#50), the more it made sense to rewrite the whole thing as a single class.  Basically, most of the code in `Optimizer` was contained in `step(OptObject)`, and that depended so heavily on `OptObject` that it seemed reasonable to have everything in a single class.  I propose that the single class should be called `Optimizer`.

I believe the current codes should satisfy the test case that you described in (#51).  It would work like this: 
```
        opts = self._initOptimizers(schemas)
        res = []
        while len(opts) > 0:
            nextOpts = []

            # take one step, energy and gradient must have been stored in optObj
            for opt in opts:    
                opt.step()

            self._batchComputeEnergyAndForces(opts)

            # evaluate step
            for opt in opts:    
                if opt.state == OPT_STATE.NEEDS_EVALUATION:
                    if opt.evaluateStep() is OPT_RESULT.CONVERGED:
                        log.info("Optmization convereged!")
                        res.append(opt.progress)
                        continue
                nextOpts.append(opt)
            if len(nextOpts) == 0: break  ######## All Done

            # step and evaluation completed, next step for remaining conformations
            opts = nextOpts

        return res
```

Please let me know what you think.

- Lee-Ping

### CODE REVIEW

**Comment by bgobbi** [comment]
Hi Lee-Ping,
I think this could work and it certainly looks simpler than what I had.
I am trying to check this out but am having trouble getting this specific version from github. Could you make this a branch I can check out? I would then try to make it work with my code.

Thanks,
Alberto

**Comment by leeping** [comment]
Hello Alberto,

I think this is already in a branch you can check out.  What is the error message that you're getting with git?

Thanks,

- Lee-Ping

**Comment by leeping** [comment]
Maybe something like this would work, though I haven't tried it locally: 
```
git remote add upstream git@github.com:leeping/geomeTRIC.git
git fetch upstream
git checkout -b unify_optimizer
```

**Comment by bgobbi** [comment]
Thanks for t[pinting this out. I had not figured out that it was a branch and was trying to checkout the specific commit but never quite got the right code. I now have it.

**Comment by leeping** [comment]
Thanks.  I've run a few regression tests over here and the performance is unchanged, but I still don't have an example where the coordinate system breaks down (looking for it now).

**Comment by bgobbi** [comment]
Hi Lee-Ping,
two change suggestions in ```optimizeGeometry()``` marked with ```AG```

```python
    def optimizeGeometry(self):
        self.calcEnergyForce()
        self.prepareFirstStep()
        # AG: this change simplifies loop but needs initilization of state to NEEDS_EVALUATION in __init__()
        while self.state not in [OPT_STATE.CONVERGED, OPT_STATE.FAILED]:
            self.step()
            if self.state == OPT_STATE.NEEDS_EVALUATION: 
                self.calcEnergyForce()
                self.evaluateStep()                  # AG: Note indent, evaluation only needed if NEEDS_EVALUATION
            #if self.state in [OPT_STATE.CONVERGED, OPT_STATE.FAILED]: 
            #  break
        return self.progress
```

**Comment by leeping** [comment]
Thanks, I agree it's an improvement and I just implemented your suggestion on the branch.

**Comment by leeping** [comment]
NEEDS_EVALUATION is already set at the bottom of step(). Should it be moved up to the top?

**Comment by bgobbi** [comment]
This is now working with my code. Thanks for making these changes. I really appreciate your work!

I have an updated version of the ```test_batch_opt.py``` and the changes to implement logging ready for a PR as soon as you have this code included in master.

**Comment by leeping** [comment]
Thanks, I'll merge this into master. :)  

For consistency with my other packages, I was wondering if you could change the name of the Logger object from `log` to `logger`, and print messages that don't contain the word "Warning" at the level of `logger.info`.

**Comment by bgobbi** [comment]
> 
> 
> NEEDS_EVALUATION is already set at the bottom of step(). Should it be moved up to the top?

I think if you adoped the changes to ```optimizeGeometry``` that I suggested you need to set it in ```__init__()``` method the top of ```step()```.
Before returning from ```step()``` the status needs to be set to the appropriate status for the action of step. this might be ```NEEDS_EVALUATION ``` or ```SKIP_EVALUATION```

**Pull request merged**
