### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by bgobbi**
This PR also includes the changes from the Split step.

I added logging and replaced all non-file based print statements with log.warning().
There is a default log.ini file in the source directory but I also added a --logINI command line switch to overwrite the log.ini file.

Alberto

### CODE REVIEW

**Comment by bgobbi** [comment]
One more thing:
I noticed that ```molecule.py```, ```nifty.py``` and ```pdb.py``` already had some logging code in place. I have not modified those because there is at least some specific configuration going on that I did not want to interfere with. I think the existing logging could be changed to the new logging that is configured by the ini file but that before doing that I wanted to check with you.
One idea I had was to have multiple ini files ```log.quiet.ini```, ```log.debug.ini``` and ```log.ini``` and have the --logINI switch take one of these values 'debug', 'quiet', <fileName.ini> or None: None would default to log.ini, fileName.ini would look for that file.

Alberto
Alberto

**Comment by leeping** [comment]
Hello Alberto,

Thank you for making these changes.  Because they also include the changes from the "Split step", I think we should resolve everything there before merging this, do you agree?

At the moment I think the main items are:

1) Ensuring the new organization does not affect performance in more "difficult" systems.  I can run some local tests on your PR that take ~1 day, let me know if I should run them now, or hold off for a while.

2) Adding a test with a "fake" batch executor that demonstrates the batch execution.

3) Anything else?

Thanks,

- Lee-Ping

**Comment by bgobbi** [comment]
That sounds about right. I have to think about how to add the fake executor. I think I will need to create a completely new command line tool. This will take me a while.

Thanks,
Alberto


ps. I ran the first minimization with NNP :))

For most examples it is working but I also saw a couple of errors. Could you take a quick look and tell me if this rings a bell? I am simply trying to minimize N-N, but I am starting at a close distance (0.6A) with strong forces.

The error starts happening at: ```geometric\internal.py:418``` where vx is a ```ndarray: [0. 0. 0.]```
Note: when running this with a debugger I see vx change a few times before ti becomes 0:
```
vx=[1.13383568 0.         0.        ]
Step    0 : Gradient = 3.412e-01/3.412e-01 (rms/max) Energy =  0.9990257415
Hessian Eigenvalues: 5.00000e-02 5.00000e-02 5.00000e-02 ... 5.00000e-02 5.00000e-02 1.48880e+04
vx=[1.13381276 0.         0.        ]
vx=[1.13383568 0.         0.        ]
Read 1 batches
Step    1 : Displace = 6.063e-06/6.063e-06 (rms/max) Trust = 1.000e-01 (=) Grad = 3.413e-01/3.413e-01 (rms/max) E (change) =  0.5286576399 (-4.704e-01) Quality = 120329.080
vx=[1.13381276 0.         0.        ]
Hessian Eigenvalues: -7.47284e+00 5.00000e-02 5.00000e-02 ... 5.00000e-02 5.00000e-02 5.00000e-02
vx=[-34132.7177167      0.             0.       ]
vx=[1.13381276 0.         0.        ]
vx=[-34132.7177167      0.             0.       ]
vx=[34132.7177167     0.            0.       ]
vx=[-34132.7177167      0.             0.       ]
vx=[34132.7177167     0.            0.       ]
vx=[-34132.7177167      0.             0.       ]
vx=[34132.7177167     0.            0.       ]
vx=[0. 0. 0.]
```

``` 
geomeTRIC\geometric\internal.py:418: RuntimeWarning: invalid value encountered in true_divide
  ev = vx / np.linalg.norm(vx)
geomeTRIC\geometric\internal.py:425: RuntimeWarning: invalid value encountered in true_divide
  exdum = xdum / np.linalg.norm(xdum)
Traceback (most recent call last):
  File "ml_qm\optimize\optimizer.py", line 382, in <module>
    sys.exit(main())
  File "ml_qm\optimize\optimizer.py", line 361, in main
    for mol in sdfOptizer:
  File "ml_qm\optimize\optimizer.py", line 204, in __next__
    self.optimizeMols(self._molBatch)
  File "ml_qm\optimize\optimizer.py", line 265, in optimizeMols
    self.gtOptimizer.step(optObj)
  File "geomeTRIC\geometric\optimize.py", line 1103, in step
    optObj.cnorm = optObj.getCartesianNorm(params.enforce, params.verbose)
  File "geomeTRIC\geometric\optimize.py", line 964, in getCartesianNorm
    return getCartesianNorm(self.X, self.dy, self.IC, enforce, verbose)
  File "geomeTRIC\geometric\optimize.py", line 142, in getCartesianNorm
    Xnew = IC.newCartesian(X, dy, verbose=verbose)
  File "geomeTRIC\geometric\internal.py", line 1456, in newCartesian
    dQ_actual = self.calcDiff(xyz2, xyz1)
  File "geomeTRIC\geometric\internal.py", line 2549, in calcDiff
    PMDiff = self.Prims.calcDiff(coord1, coord2)
  File "geomeTRIC\geometric\internal.py", line 1955, in calcDiff
    Q1 = self.calculate(coord1)
  File "geomeTRIC\geometric\internal.py", line 1905, in calculate
    answer.append(Internal.value(xyz))
  File "geomeTRIC\geometric\internal.py", line 522, in value
    return self.Rotator.value(xyz)[0]*self.w
  File "geomeTRIC\geometric\internal.py", line 429, in value
    answer = get_expmap(xsel, ysel)
  File "geomeTRIC\geometric\rotate.py", line 511, in get_expmap
    q = get_quat(x, y)
  File "geomeTRIC\geometric\rotate.py", line 276, in get_quat
    L, Q = sorted_eigh(build_F(x, y))
  File "geomeTRIC\geometric\rotate.py", line 204, in sorted_eigh
    L, Q = np.linalg.eigh(mat)
  File "C:\programs\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 1291, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "C:\programs\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 95, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
```

**Comment by leeping** [comment]
Great that things are starting to work.  :)  There are several strange things in the printout .. 

1) The displacement is 6e-6 but the energy difference is around -0.47.  That is a big energy difference for a small displacement.  Have you double-checked your units?  I think geomeTRIC uses atomic units internally for nearly everything but there are a few places where coordinates are converted to Angstrom before writing to disk.

2) I'm also seeing the `Quality` value is greater than 1e5, something I've never seen before.  This indicates the actual energy decrease is a factor of 1e5 larger than the expected decrease.  I still think this might point to an issue with units.

3) I'm able to energy-minimize N2 using a quantum chemistry engine running HF/3-21G, so I think it is not a fundamental problem with minimizing a single diatomic molecule.

**Comment by leeping** [comment]
In your printout, vx is the end-to-end displacement vector between the atoms in a linear molecule.  If it is equal to `0 0 0`, that means that somehow your atoms have collapsed to the same position.  I'm not sure what might cause this to happen, but I'd check the units first, and maybe simplify the energy / gradient function to simply return a harmonic potential before moving to the NNP.

**Comment by leeping** [comment]
By the way, the fake executor may not require creating a new command line tool.  I think you could set up the whole calculation in the testing code; it doesn't have to be something the user can easily do.

**Comment by bgobbi** [comment]
It might be that the NNP is a bit rough at some positions where it is outside of the training space. When I start from 0.8 A distance things work. i think I am doing the units right but I will double check. My believe is that Molecule.py is mostly A and the rest is only bohr.

Can you point me to some example test code you have in mind? I was thinking along the lines of the code in the examples sub directory.

**Comment by leeping** [comment]
This is an example test that @dgasmith wrote. It uses the pytest framework, so the tests are automatically executed as part of a quite.

https://github.com/leeping/geomeTRIC/blob/master/geometric/tests/test_qcengine.py

**Comment by bgobbi** [comment]
Hi Lee-Ping,
I have added test_batch_opt.py that tests and demonstrats a batch minimization using UFF in rdkit.

I followed the code you pointed out.
Alberto

**Comment by bgobbi** [comment]
I also figured out what was going on with my N2 at close distances:
The NNP is predicting the energy to decrease with decreasing distance when you get closer than 0.7A. This might be due to the training set, but there is also a limitation by design because the Behler Parrinello Atomic Environment vectors used to describe the distances have gaussians centered at distances from 0.5 to ~4.5A so the amount of information available to the network at close distances is limited.

Also:
- The big energy change is due to two things: at 0.6 A the potential curve is very steep and the NNP is confused due to the short distance.
- That also yields the high quality value, together with the hessian being a crude estimate due to this being the second cycle in the optimization.
- Both of this yield if I understand it correctly small displacement that yields to a non-existing change in the internal coordinates which yields to the error described above.

**Comment by bgobbi** [comment]
We can close this in favor of the updated one I am going to submit.

**Pull request closed without merging**
