### PR TITLE
Extracted Optmize() method to Optimizer and Optimizee classes

### PR DESCRIPTION
**Pull request by bgobbi**
I created two new classes:
Optimizer and Optimizee

Optimizer contains all the algorithmic part of the current Optimize() method and Optimizee is a container around molecule that holds all the molecule specific data required for the optimization like IC, H, Y, G,... This would allow the creation of multiple Optimizee instances that then can be optimized iteratively by calling Optimizer.step().

I did this by essentially copying code from your Optimize() method to either of the two classes.

I then replaced your Optimize() method with the 5 lines of code below.
I ran the modified code on the examples/water2_psi4 input and got identical output files.

I think the abstraction into classes could use some more rewriting but I wanted to keep it as close as possible to your current code to minimize the risk of errors due to my lack of experience with the code and novelty to optimization algorithms.
I have attached a patch file with my modifications. Would you mind taking a look to see if this goes in a direction that you think makes sense?
I retained the unmodified Optimize method but renamed it to Optimize_org

Thanks so much for working with me on this!
Alberto

def Optimize(coords, molecule, IC, engine, dirname, params, xyzout=None, xyzout2=None):
    """
    Optimize the geometry of a molecule.

    Parameters
    ----------
    coords : np.ndarray
        Nx3 array of Cartesian coordinates in atomic units
    molecule : Molecule
        Molecule object
    IC : InternalCoordinates
        Object describing the internal coordinate system
    engine : Engine
        Object containing methods for calculating energy and gradient
    params : OptParams object
        Contains optimization parameters (really just a struct)
    xyzout : str, optional
        Output file name for writing the progress of the optimization.

    Returns
    -------
    progress: Molecule
        A molecule object for opt trajectory and energies
    """

    optzer = Optimizer(engine, params, xyzout, xyzout2);
    
    optee  = Optimizee(coords, molecule, IC, engine, params.trust, dirname)
    
    while optzer.step(optee) is OPT_RESULT.NOT_CONVERGED:
        pass;
    
    return optee.progress

### CODE REVIEW

**Comment by leeping** [comment]
Thanks a lot @bgobbi , I plan on looking at this after I dig myself out of graduate admissions tonight. 

I wonder why the integrated unit tests aren't running. 

I'm also interested in @dgasmith has thoughts on the design update.  I think the separation of the main loop into `Optimizer` and `Optimizee` classes is pretty elegant.  Currently I'm not sure if `engine` needs to be used to initialize `Optimizer`.  In most of my optimizations, there is only one `engine` object and it contains the methods for computing the energy and gradient from other codes.

**Comment by dgasmith** [comment]
This is pretty cool! I like the idea of splitting out the "history" and the stepper.

I need to think about this a bit more myself. But a few comments:
 - The name `Optimizee` doesn't feel quite right. Seems something more like Trajectory or something related to history might be better, might be worth a thought.
 - Currently the `step` forces an internal engine computation. With this it could be nice to think about flexibility where I could either provide another engine or be able to set the current gradient. I think this could be accomplished later if need be.
 - Some fun ideas about being able to do multi staged optimizers at different levels of theory here.
 - It may be worth thinking about simplifying the `Optimizee` init call where things like the IC, trust, and dirname could be omitted.

**Comment by leeping** [comment]
Thanks a lot for the input @dgasmith .  :)  I guess `Optimizee / Optimizer` implies a relationship like `employee / employer`, i.e. `Optimizee` is the object that represents what's being optimized by `Optimizer`.  `OptTrajectory` is a thoughtful choice for an alternate name, but it doesn't quite convey the idea that the current structure / system is the most important.  The history is required to compute the BFGS update but it's not the core concept in the same way as a MD trajectory.

**Comment by bgobbi** [comment]
The Engine can easily be removed from the Optimizer(). It is used in a single place and we can simple use optimizee.engine.clearCalcs() instead of self.engine.clearCalcs().
However, now that I think about it this changes the internal state of the engine and thus will affect the engine of other OptTrajectory/Optimizee optimizations. This is not quite what I was aiming for.
I am not quite sure I understand what clearCalcs does and what the global variable stored_calcs is about.
We might need to move it into the OptTrajectory/Optimizee class.

Also, keeping the memory footprint of OptTrajectory/Optimizee low would be beneficial as I am intending of heaving 100's of those. But maybe not a short term need.

**Comment by leeping** [comment]
Just making sure, you are proposing that `stored_calcs` should be moved from `engine` into  `OptTrajectory/Optimizee`?

That sounds very reasonable for your application.  On the other hand, in my nudged elastic band optimizer, there is a single instance of `OptTrajectory/Optimizee` with a number of "images" (i.e. conformations of the system), each of which is calculated by a separate instance of `Engine`.  It is common in these calculations to "freeze" certain images, which means we retrieve the energy / gradients for the frozen images and recompute them for the un-frozen ones.  In that case, we need to retrieve the results from `Engine`.  

Maybe we could treat the two situations differently where `OptTrajectory/Optimizee` carries `stored_calcs` in your kind of calculation and `Engine` carries `stored_calcs` in the NEB calculation?

**Comment by leeping** [comment]
Of course, in the NEB optimizer it should be straightforward to store the energies and gradients for images separately in `OptTrajectory/Optimizee`. So it may be okay to move `stored_calcs` over entirely.

**Comment by bgobbi** [comment]
In ```Engine``` you already had [code ](https://github.com/leeping/geomeTRIC/blob/master/geometric/engine.py#L136) making ```stored_calcs``` a class variable but it is commented out. Could you explain the reason? I would like to remove the global variable and make it part of ```Engine``` as it seems you had thought about at some point.

**Comment by bgobbi** [comment]
Naming: ```OptTrajectory/Optimizee```
I am fine with both. My thinking was that the ```Optimizee``` would be a container for everything needed to perform an optimization including hessian, gradients... An object that would not be of use to anything but the Optimizer. But naming should make sense to as many people as possible. I am in favor of voting on the name with Lee-Ping having the final say.
I vote for ```Optimizee```

**Comment by leeping** [comment]
Thanks for pointing out the global variable, I had forgotten about it!  I think minimizing the number of global variables is a good idea.  It was taken out of `Engine` originally because the NEB code had several `Engine` instances but needed to find the previous QM calculations in a single place.  

I thought you were proposing to having `stored_calcs` in `OptTrajectory/Optimizee` (and not in `Engine`) because that would help with your application, and I am fine with that.  I think it will also solve the problem with NEB.  What do you think?

What do @bgobbi and @dgasmith think about `OptObject` as another candidate name?  Sorry that I am taking a while to decide on the name..

**Comment by bgobbi** [comment]
I like ```OptObject``` too.

I realized that the ```Engine``` also contains a copy of the molecule. So the current engine is molecule dependent. I have two options for my use case:

1) use a different ```Engine``` for each conformation to minimize (inside ```OptObject```). This would be the easiest, ```Engine``` does not seem to have a very big memory footprint. In this case ```stored_calcs``` could remain in ```Engine```.

2) refactor ```Engine``` to not contain a molecule. Molecule is needed because the ```Engine.calc()``` method gets only coordinates and not the atom type information. We could either change ```Engine.calc()``` to receive a molecule object with the current coordinates or pass an additional molecule object along with coords. To me passing a single molecule object that contains all info that represents a molecule (coords+AtomTypes) would be the cleaner way, but it seems like a rather big refactoring with relatively high risk, so unless you really like the idea and were thinking of going in that direction anyhow I favor option 1.

**Comment by bgobbi** [comment]
Thanks for the feedback.
This is now commited to the pull request.

**Comment by leeping** [comment]
I looked over all of the changes and I'm running some manual tests now on some slightly larger systems and with different engines.  The plan is to merge tonight or early tomorrow if the performance is the same.  :)

**Pull request merged**
