### PR TITLE
Fix qccnv

### PR DESCRIPTION
**Pull request by sjrl**
Updated the convergence criteria for qchem convergence to correctly use gmax, and dmax or energy as described in the qchem manual. http://www.q-chem.com/qchem-website/manual/qchem51_manual/sect-equi.html

### CODE REVIEW

**Comment by leeping** [comment]
Hi Sebastian,

I remember when writing that part of the code, I was actually never able to reproduce the exact numbers that Q-Chem was printing out when checking the convergence criteria.  I tried to take the maximum gradient component in any Cartesian coordinate as well as the maximum atomistic gradient norm (i.e. taking the norm of the force components in groups of three and taking the maximum over those), and both were significantly larger than what Q-Chem was printing out.  Thus, I still don't know exactly what Q-Chem is calculating for the max gradient / max displacement when checking convergence.  

For example, for the "water6" example, Q-Chem prints this out on the first step (after the first gradient computation and taking a single step, but before the second gradient computation):

```
                             Maximum     Tolerance    Cnvgd?
         Gradient           0.044641      0.000300      NO
         Displacement       0.115513      0.001200      NO
         Energy change     *********      0.000001      NO
```

And geomeTRIC prints this out on the first step (after the first gradient computation and before taking a single step):

```
Step    0 : Gradient = 4.474e-02/6.041e-02 (rms/max) Energy = -449.7940123500
```

Thus, you see the "maximum gradient component" from Q-Chem prints out is actually smaller than the "gmax" from geomeTRIC, and is in fact closer to "grms" from geomeTRIC.  That is why I did not adopt the smaller values of `gmax=3e-4` and `dmax=1.2e-3` in geomeTRIC when using Q-Chem style convergence criteria, because I thought that would actually make the convergence criteria even tighter compared to what Q-Chem is actually doing.

As part of this fix, could you try to reproduce the "maximum displacement / maximum gradient" numbers that Q-Chem is printing out?  Even though the codes take different optimization steps, you can always look at the maximum gradient for the first step.

Thanks,

- Lee-Ping

**Comment by leeping** [comment]
Hi Sebastian,

Sounds good. If you have any trouble matching the gmax / dmax values that Molpro is printing out, please let me know. I have access to the Molpro source code so it should be easier to diagnose issues.

- Lee-Ping

**Comment by sjrl** [comment]
Hi Lee-Ping,

Quickly running a Molpro optimization using the same water6 example I get the following output from Molpro. The gradient information that is printed is before taking a step even though they provide the energy of the molecule after the step has been taken. 

`ITER.   ENERGY(OLD)    ENERGY(NEW)      DE          GRADMAX     GRADNORM    GRADRMS     STEPMAX     STEPLEN     STEPRMS   CPU-time
  1  -449.79401200  -449.81270795    -0.01869595  0.09771994  0.18983879  0.00395497  0.15873777  0.30000000  0.07071068      1.61`

All I can determine is that the units of the gradient are in Hartree/Angstrom vs. Hartree/bohr. However, I cannot figure out how to get that exact value of GRADMAX. The full gradient vector is provided as 
`Variable                      Last           Current        Next           Gradient       Hessian
E(RHF-SCF000) / Hartree     0.00000000  -449.79401200  -449.81139269
GX1 / ANGSTROM              0.00000000     0.85591000     0.85324077     0.07233175    -0.00000000
GY1 / ANGSTROM              0.00000000    -1.38236000    -1.37619771     0.02439692    -0.00000000
GZ1 / ANGSTROM              0.00000000     0.31746000     0.32273470     0.00733000    -0.00000000
GX2 / ANGSTROM              0.00000000     1.67524000     1.68246462    -0.05741910    -0.00000000
GY2 / ANGSTROM              0.00000000    -1.84774000    -1.85816438     0.02949540    -0.00000000
GZ2 / ANGSTROM              0.00000000     0.48580000     0.49523546    -0.01441264     0.00000000
GX3 / ANGSTROM              0.00000000     1.11761000     1.13443982    -0.02433836     0.00054665
GY3 / ANGSTROM              0.00000000    -0.46843000    -0.44566585    -0.06331878     0.00081725
GZ3 / ANGSTROM              0.00000000     0.20575000     0.25306428    -0.00964441     0.00164254
GX4 / ANGSTROM              0.00000000    -1.09863000    -1.11728289     0.06746276     0.00209700
GY4 / ANGSTROM              0.00000000    -0.85837000    -0.86560884     0.06360661     0.00222194
GZ4 / ANGSTROM              0.00000000     2.17319000     2.19714581    -0.06473349     0.00298423
GX5 / ANGSTROM              0.00000000    -0.40310000    -0.41302814    -0.04938136     0.00384176
GY5 / ANGSTROM              0.00000000    -1.14608000    -1.15114539     0.00613973     0.00570997
GZ5 / ANGSTROM              0.00000000     1.58184000     1.58568693     0.04412561     0.00756676
GX6 / ANGSTROM              0.00000000    -1.08511000    -1.07974880    -0.01329697     0.00888238
GY6 / ANGSTROM              0.00000000     0.09683000     0.10644699    -0.06922090     0.01340617
GZ6 / ANGSTROM              0.00000000     2.11282000     2.11486776     0.01472161     0.01596092
GX7 / ANGSTROM              0.00000000     1.86448000     1.82039547     0.09741042     0.01815562
GY7 / ANGSTROM              0.00000000     1.22018000     1.15840335     0.02669808     0.02350320
GZ7 / ANGSTROM              0.00000000     1.33311000     1.28203820    -0.05319287     0.02854899
GX8 / ANGSTROM              0.00000000     2.01047000     2.02302508    -0.02649633     0.03138947
GY8 / ANGSTROM              0.00000000     1.88292000     1.90404425    -0.04836161     0.03978042
GZ8 / ANGSTROM              0.00000000     0.65806000     0.67323080     0.04939289     0.04556833
GX9 / ANGSTROM              0.00000000     2.64205000     2.69620957    -0.07462618     0.05343250
GY9 / ANGSTROM              0.00000000     0.66326000     0.70036166     0.02457380     0.06087234
GZ9 / ANGSTROM              0.00000000     1.29479000     1.31938630     0.00813556     0.06741210
GX10 / ANGSTROM             0.00000000     0.43601000     0.42791792     0.05365245     0.07038898
GY10 / ANGSTROM             0.00000000     0.85911000     0.88192274    -0.09068667     0.07956360
GZ10 / ANGSTROM             0.00000000    -1.79901000    -1.79850117    -0.02102737     0.08248987
GX11 / ANGSTROM             0.00000000     1.29527000     1.31356458    -0.06324440     0.08890680
GY11 / ANGSTROM             0.00000000     0.59436000     0.60119693     0.02844545     0.15116807
GZ11 / ANGSTROM             0.00000000    -1.47066000    -1.49950828    -0.00839214     0.16755977
GX12 / ANGSTROM             0.00000000     0.13556000     0.12741601     0.01100827     0.17462303
GY12 / ANGSTROM             0.00000000     0.11122000     0.11703917     0.05527804     0.45810160
GZ12 / ANGSTROM             0.00000000    -2.31537000    -2.32277965     0.03422977     0.76046766
GX13 / ANGSTROM             0.00000000    -0.80093000    -0.83239624     0.10512641     0.88065987
GY13 / ANGSTROM             0.00000000    -2.09113000    -2.09850097     0.04378659     0.88110980
GZ13 / ANGSTROM             0.00000000    -1.57300000    -1.59078155     0.00081214     0.88622008
GX14 / ANGSTROM             0.00000000    -0.22032000    -0.22558191    -0.04920688     0.95124413
GY14 / ANGSTROM             0.00000000    -1.82977000    -1.85194890    -0.01497380     0.98548224
GZ14 / ANGSTROM             0.00000000    -0.85828000    -0.86480267    -0.04456401     1.10320152
GX15 / ANGSTROM             0.00000000    -0.32806000    -0.31804220    -0.04671819     4.77904726
GY15 / ANGSTROM             0.00000000    -1.84581000    -1.86998450    -0.01529274     4.78571598
GZ15 / ANGSTROM             0.00000000    -2.36826000    -2.38928143     0.05505101     4.78783957
GX16 / ANGSTROM             0.00000000    -1.49676000    -1.49320553    -0.01709464     4.81317223
GY16 / ANGSTROM             0.00000000     2.26791000     2.27677199    -0.09612701     4.85099367
GZ16 / ANGSTROM             0.00000000    -0.32954000    -0.30428155    -0.05160523     4.95750178
GX17 / ANGSTROM             0.00000000    -0.84679000    -0.84415606    -0.03821759     5.68119157
GY17 / ANGSTROM             0.00000000     1.69408000     1.70393617     0.04934683     5.68866102
GZ17 / ANGSTROM             0.00000000    -0.73513000    -0.75679976     0.03897538     5.69667781
GX18 / ANGSTROM             0.00000000    -2.32526000    -2.32759207     0.05304794     5.70329876
GY18 / ANGSTROM             0.00000000     1.79846000     1.78573329     0.04621407     5.73118472
GZ18 / ANGSTROM             0.00000000    -0.42670000    -0.42978419     0.01479817     5.76126232`

**Comment by leeping** [comment]
Hi Sebastian,

From looking at the source code, it looks like GRADMAX is calculated as the maximum over the absolute value of all of the individual elements of the Cartesian gradient vector, i.e. in numpy, we'd have `gradmax = np.max(np.abs(g.flatten()))`. However, that does not match up exactly with the numbers you're providing, although it comes close. 

I would suggest double-checking that the printed GRADMAX corresponds to the "old" gradient and not the "new" one. For example, you could check if the maximum component of the gradient of the "new" structure matches with the GRADMAX.

If that doesn't help, can you please upload your input file and I can insert some print statements into the source code?

Thanks,

- Lee-Ping

**Comment by sjrl** [comment]
Hi Lee-Ping,

I also have access to Molpro's source code and from what I can tell (using the attached input file), the geometry optimization is driven by `./src/opt/opt_drv.F`. Specifically the subroutine `modelopt` (defined in `./src/opt/modelopt.F`) is called from `opt_drv`, which then determines the value of GRADMAX. From what I can see the optimization is performed in normal coordinates so the GRADMAX value is determined as the maximum value over the absolute value of the normal coordinate gradient vector. However, only the cartesian gradient vector is printed to the log file.  This might also explain what is happening in Q-Chem. 

Some relevant variables inside `modelopt.F` are:
n --> number of normal modes; declared in src/common/coptg
g(n,npt) --> stores gradient vector
gradmx --> stores maximum gradient value

Some additional details:
1. The attached input uses the RFO method (Molpro's default).
2. The `opt_rf` subroutine called  within the subroutine `modelopt` does not edit the gradient vector by default unless the variable `linsearch` is greater than or equal to 0. It is -1 by default.
3. The specific subroutine that determines GRADMAX is `modelconv` which is called from `modelopt`.

[water6_molpro_input.txt](https://github.com/leeping/geomeTRIC/files/2032932/water6_molpro_input.txt)

**Comment by sjrl** [comment]
Hi Lee-Ping,

Sorry for not clarifying in my earlier comment. I had already added print statements and I found for the input file I've been using (water6_molpro_input.txt) does use `modelcnv` and not `optcnv`. The reason I suspect the gradient to projected along the normal coordinates is because the way `gradmx` is being determined in `modelcnv`. Specifically they loop over all elements in the gradient vector using the the do loop 'do 800 j=1,n' where I found `n` to be equal to 48 for the given input file instead of the expected 54 for the 18 atoms. So I assumed the 48 came from the 3N-6 normal modes. 

I'll look further into this and see if I can reproduce the max gradient value by projecting the provided cartesian gradient onto the normal modes. 

Thanks,
Sebastian

**Comment by leeping** [comment]
Hi Sebastian,

Thanks for clarifying.  I should note that the geomeTRIC optimization doesn't calculate a Cartesian Hessian matrix at the moment (or calculate the normal modes).  

If this is what you want geomeTRIC to support, you will need to construct a Cartesian model Hessian at the start and make BFGS updates to it as the optimization progresses (even though you aren't using it for the optimization).  This could probably be implemented by copying and modifying all of the lines that update the internal coordinate Hessian.  You also need to add some code to get the normal modes, identify the modes that correspond to the translations and rotations of the whole system, then do the projection of the gradient onto the other (vibrational) modes.  

The easy way out is to just to take the maximum element of the Cartesian gradient vector, and write a comment in the code that Molpro convergence criteria are only implemented approximately.  It would still be nice to double check that the maximum Cartesian gradient component is close to the maximum normal mode gradient component in a few different test cases (it seems to be true for the case you provided above).

Thanks,

- Lee-Ping

**Comment by leeping** [comment]
Just following up on this, what do you think is the best way forward?  I think the best way is simply to take the maximum element of the Cartesian gradient vector.

**Comment by sjrl** [comment]
Hi Lee-Ping,

The two commits changed back the convergence criteria for Q-Chem and added a new option for Molpro convergence criteria. I also explicitly noted that the Molpro criteria is approximate since the check is done in cartesian coordinates.

Best,
Sebastian

**Comment by leeping** [comment]
Thanks again (and sorry for the late response).  Merging. :)

**Pull request merged**
