### PR TITLE
Log to logger

### PR DESCRIPTION
**Pull request by bgobbi**
I changed all the loggers to be named ```logger```. However in doing so i had to remove your custom code that configured specific loggers in ```nifty.py, PDB.py, molecule.py```.

### CODE REVIEW

**Comment by leeping** [comment]
Thanks a lot for creating the new PR.  I am sure this is a good change and I plan on merging it, but I'd also like to take this chance to discuss the custom loggers.

The custom loggers are there because `nifty.py, PDB.py, molecule.py` are taken from ForceBalance. These files are general-purpose modules that I copied to geomeTRIC to remove the dependency on ForceBalance, and I periodically sync them manually to make sure they are up to date in both packages. In addition, the modules are designed to work as standalone files i.e. if someone doesn't have either geomeTRIC or ForceBalance installed, they should still be able to import them.  

To meet the above goals and to keep things manageable, I would prefer to avoid having different versions of the code in different packages.  In other words, it'd be best to have package-specific behavior in "if" blocks such as `if "geometric" in __name__:`.  Do you think it would be possible to do this for just those three files?

**Comment by leeping** [comment]
I just created a PR to your branch https://github.com/bgobbi/geomeTRIC/pull/1 containing some changes to `nifty.py, PDB.py, molecule.py` that should meet the needs I noted above.  Please let me know if it works for you.

**Comment by bgobbi** [comment]
I have incorporated your changes and identified a couple more print statements.
Thanks!

**Comment by bgobbi** [comment]
I tested the logging to a file I think it works as you suggested.
Alberto

**Comment by leeping** [comment]
This looks really great.  I have one last request, could you please change the Hessian eigenvalues from debug to info?  These are very useful when the optimization has unexpected behavior so I like to have them printed by default.

**Comment by bgobbi** [comment]
Hessian is now info
Alberto

**Comment by leeping** [comment]
Thank you very much - merging.

**Pull request merged**
